# Generated by Django 5.0.6 on 2024-06-04 08:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('a_posts', '0003_tag_post_tag'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='tag',
            new_name='tags',
        ),
    ]
