# Generated by Django 5.0.6 on 2024-07-10 11:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('a_landingpages', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Landinpage',
            new_name='LandingPage',
        ),
    ]
